# Generated by Django 6.0.3 on 2026-04-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='gander',
            new_name='gender',
        ),
    ]
