# Generated by Django 6.0.3 on 2026-04-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
