# Generated by Django 6.0.3 on 2026-05-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
